# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1766, 1274)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 1761, 1251))
        self.tabs.setObjectName("tabs")
        self.live_rab = QtWidgets.QWidget()
        self.live_rab.setObjectName("live_tab")
        self.pushButton = QtWidgets.QPushButton(self.live_tab)
        self.pushButton.setGeometry(QtCore.QRect(790, 1090, 231, 101))
        self.pushButton.setObjectName("start_live_button")
        self.live_label = QtWidgets.QLabel(self.live_rab)
        self.live_label.setGeometry(QtCore.QRect(160, 140, 1341, 821))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.live_label.sizePolicy().hasHeightForWidth())
        self.live_label.setSizePolicy(sizePolicy)
        self.live_label.setScaledContents(True)
        self.live_label.setObjectName("live_label")
        self.tabs.addTab(self.live_rab, "")
        self.capture_tab = QtWidgets.QWidget()
        self.capture_tab.setObjectName("capture_tab")
        self.tabs.addTab(self.capture_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1766, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Start Live View"))
        self.live_label.setText(_translate("MainWindow", "TextLabel"))
        self.tabs.setTabText(self.tabs.indexOf(self.live_rab), _translate("MainWindow", "Tab 1"))
        self.tabs.setTabText(self.tabs.indexOf(self.capture_tab), _translate("MainWindow", "Tab 2"))
